datastore:
  build: .
  restart: always
  volumes:
    - /home/ktiedt/Plex:/home/ktiedt/Plex
sabnzbd:
  image: ktiedt/sabnzbd
  restart: always
  volumes:
    - /home/ktiedt/.htpc-suite/sabnzbd:/config
  volumes_from:
    - datastore
  ports:
    - 9000:8080
couchpotato:
  image: ktiedt/couchpotato
  restart: always
  volumes:
    - /home/ktiedt/.htpc-suite/couchpotato:/config
  volumes_from:
    - datastore
  ports:
    - 9002:5050
  links:
    - sabnzbd
plex:
  image: ktiedt/plex
  restart: always
  volumes:
    - /home/ktiedt/.htpc-suite/plex:/config
  volumes_from:
    - datastore
  ports:
    - 32400:32400
nzbdrone:
  image: ktiedt/nzbdrone
  restart: always
  environment:
    - XDG_CONFIG_HOME=/config
  volumes:
    - /home/ktiedt/.htpc-suite/nzbdrone:/config
    - /home/ktiedt/Plex:/home/ktiedt/Plex
  volumes_from:
    - datastore
  ports:
    - 9001:8989
  links:
    - sabnzbd
